apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volitveni-vodic
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/volitve)$ $1/ redirect; # add trailing slash
spec:
  tls:
    - hosts:
        - vodici.djnd.si
      secretName: volitveni-vodic-tls
  rules:
    - host: vodici.djnd.si
      http:
        paths:
          - path: /volitve(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: volitveni-vodic
                port:
                  number: 80
