apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volitveni-vodic
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /volitve {
        return 302 $uri/;
      }
spec:
  tls:
    - hosts:
        - vodici.djnd.si
      secretName: volitveni-vodic-tls
  rules:
    - host: vodici.djnd.si
      http:
        paths:
          - path: /volitve/(.*)
            pathType: Prefix
            backend:
              service:
                name: volitveni-vodic
                port:
                  number: 80
