apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: volitveni-vodic
    newName: rg.fr-par.scw.cloud/djnd/volitveni-vodic
    newTag: '00aa1bdd9eaa6e30c679664355ac1679f4657f4b'
