name: Build and publish Docker image
on:
  push:
    branches:
      - 'predsednik-2022-drugi-krog'
jobs:
  push_to_registry:
    name: Build and push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Scaleway
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/djnd
          username: nologin
          password: ${{ secrets.SCW_SECRET_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            rg.fr-par.scw.cloud/djnd/volitveni-vodic-predsednik-2022-drugi-krog:${{ github.sha }}
            rg.fr-par.scw.cloud/djnd/volitveni-vodic-predsednik-2022-drugi-krog:latest

      - name: Update image versions in kustomize/kustomization.yaml
        run: |
          sed -i "s/newTag: .*\+/newTag\: '${{ github.sha }}'/" kustomize/kustomization.yaml

      - name: Commit and push new image versions
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Update image versions in kustomize/kustomization.yaml'
